epochs: 75
imgsz: 640
verbose: false
batch: 16       
device: 0
epochs: 100
workers: 2
cache: disk

optimizer: AdamW
lr0: 0.001
weight_decay: 0.01
cos_lr: true
warmup_epochs: 3
patience: 25

augment: true
mosaic: 0.5
close_mosaic: 10
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0